version: '3.11'

services:
  app:
    image: app
    build: .
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached

    command: sh -c "python rindustest/manage.py migrate &&
                    python rindustest/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - .env

volumes:
  postgres-data:
